1st markup done
yuta-san765/markup-practice1 pull request #1
Opened 2020-03-07 05:21 UTC by yuta-san765

やったこと：
手紙のマークアップしました。

チェックしてほしいところ：
・addressタグを使って差出人の住所をマークアップしようとしましたが、見本と異なりイタリック体になってしまったのでpタグをつかってあります。どうするべきか教えて欲しいです。
・GitHubの使い方の練習も兼ねてます。間違いがあれば教えてください。

2020-03-07 06:39 UTC, piasoratech requested changes
コメントをしたので確認をお願いします。
`address`タグを使用すると斜体になってしまう件ですが、タグの仕様なので気にせず使用してもらって構わないです。

2020-03-07 06:39 UTC, piasoratech commented on markup_kadai_01.html
> +      </p>
ここは`div`タグにクラスを付与して、各行に対して１行ずつ`p`タグをあてるようにしてください

2020-03-07 06:39 UTC, piasoratech commented on markup_kadai_01.html
> +        恵比寿ガーデンプレイス
ここも上記同様１行ずつ`p`タグをあてるようにしてください

2020-03-07 06:39 UTC, piasoratech commented on markup_kadai_01.html
> +      <h1>
見出しの`h1～h6`タグを使うときには`section`タグも使うようにしましょう

2020-03-07 06:39 UTC, piasoratech commented on markup_kadai_01.html
> +      <h2>
ここも同様に`section`タグを使用しましょう

2020-03-07 06:39 UTC, piasoratech commented on markup_kadai_01.html
> +
`main`タグを使用しましょう

2020-03-07 07:13 UTC, yuta-san765 reviewed
指摘された点を修正しました。コメントお願いします。

2020-03-07 07:13 UTC, yuta-san765 commented on markup_kadai_01.html
>        </p>
ここもaddressで囲う必要がありますか？

2020-03-07 07:13 UTC, yuta-san765 commented on markup_kadai_01.html
>        </p>
ここもsectionタグで囲う必要がありますか？

2020-03-09 03:45 UTC, nozomi71 commented on markup_kadai_01.html
> +          </p>
1行にまとめましょうか
複数行の場合は、この書き方のほうが可読性高いです

2020-03-09 03:46 UTC, nozomi71 commented on markup_kadai_01.html
>        </p>
ここは日付なので必要ないです！

2020-03-09 03:46 UTC, nozomi71 commented on markup_kadai_01.html
>        </p>
`section`タグは見出しのあるブロックに使用するのでここは必要ないです！

2020-03-09 03:57 UTC, yuta-san765 commented
１行にまとめられるタグは1行にまとめるよう修正しました。

2020-03-09 04:03 UTC, umurajim approved these changes
良いかと！

2020-03-09 04:15 UTC, merged